FROM node:22-alpine

WORKDIR /app

# Installer dépendances
COPY package*.json ./
RUN npm install

# Copier le code
COPY . .

# Exécuter en mode dev
#CMD ["npm", "run", "start:dev"]
CMD ["npx", "nest", "start", "--watch"]